---
version: '3'
services:
  mysql:
    image: mysql:5.7.8
    env_file:
      - .env

  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:80"
    env_file:
      - .env