---
version: '3'
services:
  mysql:
    image: mysql:5.7.8
    env_file:
      - .env

  microservice:
    image: microservice
    ports:
      - "8081:80"
      - "8082:443"
    env_file:
      - .env

  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:80"
      - "443:443"

    env_file:
      - .env