route:
  receiver: 'mail'
  repeat_interval: 2m
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:587'
        auth_username: 'kevinbillerach@gmail.com'
        auth_password: "essyiojgcnexqcpg"
        from: 'kevinbillerach@gmail.com'
        to: 'kevinbillerach@gmail.com'
