---
version: '3'
services:
  microservice:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
      - "8082:443"
    networks:
      - projetB

networks:
  projetB:
    external: true