---
version: '3'
services:
  microservice:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - projetB

networks:
  projetB:
    external: true